language: java

sudo: false

cache:
  directories:
    - $HOME/.m2
    - /^.*\\target\\cobertura\\.*$/

jdk:
  - oraclejdk8

os:
  - linux

script:
  - mvn clean install
  - mvn cobertura:cobertura

after_script:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - dev
