language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

os:
  - linux

script:
  - mvn test
  - mvn cobertura:cobertura

before_cache:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - dev
