language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

os:
  - linux

script: "mvn clean install"

after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - dev
